console.log("Once in a galaxy far far away.")
console.log("There was a planet named 惑星 also know as wakusei.")
console.log("In a small town there lived a jedi.")
console.log("But not just any jedi. A jedi ronin.")
console.log("The sith tried to hunt them down.")
console.log("But they were smart en strong.")
console.log("The sith lord came to the planet to kill the jedi ronin.")
console.log("The sith lord threatened to kill the villagers for the jedi to come out of his small house.")
console.log("A man with robes on came out of his small house.")
console.log("The sith lord asked: Who are you?")
console.log("Then the stranger said: I'm no one.")
console.log("The sith lord turn her lightsaber on.")
console.log("She said i wasn't asking.")
console.log("She rushed towards the stranger.")
console.log("The stranger pulled his lightsaber.")
console.log("But it was red.")
console.log("The sith lord says: But.. but it's  red.")
console.log("They fought for a while. But eventually the Jedi ronin won.")
console.log("The sith lord asked: Why is your light saber red?")
console.log("The jedi ronin pulled a red crystal out of his pocket. I hunt sith.")
console.log("The sith lord dies in front of him.")
console.log("The end")
console.log("Story based on Star Wars visions")